<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutDir>../../CuraEngineConnection/build/$(Configuration)</OutDir>

    <Title>CuraEngineConnectionTest</Title>
    <Description>CuraEngineConnectionTest</Description>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="$(OutDir)\CuraConnectionInterface.dll" />
    <Reference Include="$(OutDir)\CuraEngineParametersLibrary.dll" />
    <Reference Include="$(OutDir)\CuraEngineNetWrapper.dll" />

    <PackageReference Include="EncySoftware.CAMAPI.SDK.Net" Version="1.2.1-rc.9" /> 
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NCalcSync" Version="3.12.0" />
  </ItemGroup>
</Project>
