<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Title>CuraEngineOperation</Title>
    <Description>CuraEngineOperation</Description>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>CS8603</NoWarn>
    <OutDir>../CuraEngineConnection/build/$(Configuration)</OutDir>
    <CAMPath>C:/Program Files/ENCY Software/ENCY NB/Bin64</CAMPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="$(OutDir)\CuraConnectionInterface.dll" />
    <ProjectReference Include="..\CuraEngineNetWrapper\CuraEngineNetWrapper.csproj" />
    <ProjectReference Include="..\CuraEngineParametersLibrary\CuraEngineParametersLibrary.csproj" />

    <PackageReference Include="EncySoftware.CAMAPI.SDK.Net" Version="1.2.1-rc.9" />
  </ItemGroup>
</Project>